### ISSUE TITLE
intel edison 

### ISSUE THREAD

**Issue by aafeliz** [IanHarvey/bluepy#101]
any idea if it will work for yocto 2.1 on the intel edison?

**Comment by IanHarvey** [comment]
There's an Intel document at http://download.intel.com/support/edison/sb/edisonbluetooth_331704004.pdf which suggests that the regular BlueZ 5.x tools will work. The bluepy code is based on BlueZ 5.x, so it ought to work fine. 

It looks like Edison is infested by systemd, so you might find there's some system setup you need to do before anything will work, though...

**Comment by IanHarvey** [comment]
Sadly, time was against us, and I never got an Edison to play with before they were discontinued by Intel. It's therefore unlikely that I'll be able to help with any Edison or Yocto-specific issues.

Cheers
Ian
