### ISSUE TITLE
Issue with BLE pairing

### ISSUE THREAD

**Issue by antonkluev** [IanHarvey/bluepy#102]
Guys,

i try to connect RPI via USB BLE Dongle to BLE Modul on my Arduino... ive tryed all the tutorials in internet, and googled all the issues that i received, but no success! Even i purchased another BLE USB Dongle in Case that the another one is defect or something like this... 

All i need is to send a String over BLE Serial from RPI to Arduino, thats all...
The Arduino setup working with my iPhone! If i send a "1" over "Serial App" from iPhone to Arduino, a LED goes on with an feedback "LED On", if i send "0" than off with feedback "LED Off". 
Mainly ive used this tutorial http://www.jaredwolff.com/blog/get-started-with-bluetooth-low-energy/
And i receive allways the same error: 

```
antonkluev.pi ~ $ sudo hcitool lescan
LE Scan ...
00:15:83:00:41:3A (unknown)
antonkluev.pi ~ $ sudo gatttool -b 00:15:83:00:41:3A -I -t random
[00:15:83:00:41:3A][LE]> connect
Attempting to connect to 00:15:83:00:41:3A
Error: connect: Connection refused (111)
[00:15:83:00:41:3A][LE]>
```

if i erase "-t random" than the error is the same... i have an assumption that the "-t" flag not working... I am new in this technology, therefore, realy sorry for my not knowing, i need realy help...

**Comment by 0xFACE** [comment]
Try
<code>btmgmt le on</code>
The btmgmt command is part of bluez package, but is not installed by default.

**Comment by antonkluev** [comment]
thank you 0xFACE :) i know what was wrong! My kernel version was 4.+ and this was an issue. Somehow this kernel version is not compatible with Bluez or BLE.. don't realy know )) 
Ive installed wheezy Raspbian with commone 3.18.11 and "it works like a charm" XD

Did you try to run BLE on 4.+ kernel?

**Comment by 0xFACE** [comment]
Yes ;-)
<code>
Linux raspberrypi 4.1.15+ #831 Tue Jan 19 18:36:09 GMT 2016 armv6l GNU/Linux
</code>

**Comment by antonkluev** [comment]
omg! 0xFACE! i wannt to kiss you, man! Jesus! It works! You don*t have an idea, how long ive sittet with this issue... and now you enter with you simple solution! Crazy :)

once again - thank you!

**Comment by 0xFACE** [comment]
Before I found the solution just by playing with bluez commands I spend few weeks googling without success.
I'm glad to see it works also for you ;-)

**Comment by 957919019** [comment]
you can try Use 'SystemClock.sleep(500)'  to avoid operation to fast

**Comment by saviourcode** [comment]
> Try
> `btmgmt le on`
> The btmgmt command is part of bluez package, but is not installed by default.

Thanks alot, it worked!

**Comment by knito** [comment]
> Try
> `btmgmt le on`
> The btmgmt command is part of bluez package, but is not installed by default.

This is the solution to see my BLE device in the list! Many thanks!!!!

**Comment by Jackfritt** [comment]
Had the same Problem and after using this with a BT 4.0 noname Dongle and PC hardware with latest bluez5.54 it worked like a charm. One day searching and trying hard! Thx.
