### ISSUE TITLE
Can bluepy act as different roles?

### ISSUE THREAD

**Issue by namoaton** [IanHarvey/bluepy#109]
Can bluepy act as different roles?

**Comment by IanHarvey** [comment]
No, there isn't any support for acting as a Peripheral at the minute.
A GATT server will be quite a different 'shape' to the current API. I'm debating whether to keep it in the existing framework (with `bluepy-helper`), or whether it should be a complete re-implementation based on `asyncio` or similar.

**Comment by namoaton** [comment]
It would be greatfull  if bluepy can act as peripherial. I can help to test such feature

**Comment by smdjeff** [comment]
BlueZ is just about impossible to get working as a peripheral. I think something was deprecated that causes "register GATT service with handle" when the master tries to read services. It sure would be nice to have BluePy and less BlueZ dependent alternative for the new Raspberry Pi 3 which has BT and LE out of the box!

**Comment by IanHarvey** [comment]
I've spent quite a lot of effort trying to get BlueZ peripheral code to do anything interesting, without success.

I'm beginning to think that writing a whole Python stack from scratch is the way to go. I note there's a Javascript module (https://github.com/sandeepmistry/bleno) which does just this, and doesn't use anything like BlueZ.

**Comment by wernerterreb** [comment]
I'm also at the moment starting to doubt suitability of Bluez for the stuff I'm trying to do.  Basically I need the pair securely with a peripheral device that requires exchange of Identity Resolving Keys (IRK).  But try as I like, I cannot seem to make it work on Bluez.   But it was relatively trivial to do on Android.

**Comment by IanHarvey** [comment]
Closing this issue. `bluepy` is not going to support the Peripheral role in future versions.

I'd recommend interested parties look at the `bleson` project (current first drafts at https://github.com/TheCellule/python-bleson/blob/wk_draft_experiment/README.rst) for Python beacon and peripherals support.

Thanks
Ian
