### ISSUE TITLE
Notification with multiple connections

### ISSUE THREAD

**Issue by namoaton** [IanHarvey/bluepy#110]
Notification with multiple connections. How can we easily distinguish  without cHandle, but with  for example addr?

**Comment by IanHarvey** [comment]
The easiest thing is just to add a reference to the `Peripheral` in your delegate class, e.g.

    class MyDelegate(DefaultDelegate):
        def __init__(self, peripheral):
            DefaultDelegate.__init__(self)
            self.peripheral = peripheral
    
    ...
    dev = Peripheral(addr)
    dev.setDelegate( MyDelegate(dev) )

You will then have a `self.peripheral` object available in your delegate's `handleNotification`.

**Comment by namoaton** [comment]
I will try it today and then write here about my experience

**Comment by namoaton** [comment]
when I print peripheral.addr  it is returned None

**Comment by namoaton** [comment]
I proposed to add get_addr() function to Peripheral class
