### ISSUE TITLE
is Peripheral's connect function thread safe?

### ISSUE THREAD

**Issue by hdkim** [IanHarvey/bluepy#126]
when I tried to connect to two peripherals in same time using thread, it seems not working.

The first peripheral's connection was dropped

is there a way to connect more than two periperals in same time?

**Comment by IanHarvey** [comment]
It's slightly complicated: 

- You can't try to make a connection to more than one peripheral at the same time. This isn't a threading problem, it's a limitation on the Bluetooth Host Controller Interface. Issue #57 has more details. I think this might be why you are seeing the connection failing.
- A ```Peripheral``` object itself isn't re-entrant: when one method on the object is executing, you must not call any other method from a different thread.

You can, however, have more than one thread, each with its own separate ```Peripheral``` object.
