### ISSUE TITLE
read/write of HM-10 BLE serial module

### ISSUE THREAD

**Issue by erazor83** [IanHarvey/bluepy#13]
Hi there!

I'm currently trying to read/write serial data from a HM10-BLE module.

The module is connected to my USB via an FTDI chip and I can read/write AT-commands.

I'm already able to write data via Bluetooth and can see the chars via my usb-interface but it does not seem to work the other way around.

Here are some details:
<pre>
s9 bluepy # python btle.py 7C:66:9D:9A:6F:90
Connecting to: 7C:66:9D:9A:6F:90
Service <uuid=Generic Attribute handleStart=12 handleEnd=15> :
    Characteristic <2a05>
    -> Error from Bluetooth stack (comerr)
Service <uuid=Generic Access handleStart=1 handleEnd=11> :
    Characteristic <Device Name>
    -> 'HMSoft'
    Characteristic <2a01>
    -> '\x00\x00'
    Characteristic <2a02>
    -> '\x00'
    Characteristic <2a03>
    -> '\x00\x00\x00\x00\x00\x00'
    Characteristic <2a04>
    -> 'P\x00\xa0\x00\x00\x00\xe8\x03'
Service <uuid=ffe0 handleStart=16 handleEnd=65535> :
    Characteristic <ffe1>
    -> '\x00'
</pre>

I have 3 services with differet characteristics:
<pre>
== 00001801-0000-1000-8000-00805f9b34fb ==
[<btle.Characteristic instance at 0x7f936f6c5f38>]
== 00001800-0000-1000-8000-00805f9b34fb ==
[<btle.Characteristic instance at 0x7f936f6c5fc8>, <btle.Characteristic instance at 0x7f936761e098>, <btle.Characteristic instance at 0x7f936761e128>, <btle.Characteristic instance at 0x7f936761e1b8>, <btle.Characteristic instance at 0x7f936761e248>]
== 0000ffe0-0000-1000-8000-00805f9b34fb ==
[<btle.Characteristic instance at 0x7f936761e2d8>]
</pre>

So my data-channel seems to be 0000ffe0, writing here ends at my USB side.

Does anybody know how I'd be able to read? The read() on the data-channel just returns None.

My code:
<pre>
import struct
from btle import UUID, Peripheral

class HM10(Peripheral):
	_ctrlUUID=UUID("00001800-0000-1000-8000-00805f9b34fb")
	_dataUUID=UUID("0000ffe0-0000-1000-8000-00805f9b34fb")
	
	def __init__(self, addr):
		Peripheral.__init__(self,addr)
		self.discoverServices()
		for cUUID in self.services:
			print("== %s =="%str(cUUID))
			print(self.getServiceByUUID(cUUID).getCharacteristics())
				
		self.ctrl_SRV=self.getServiceByUUID(self._ctrlUUID)
		self.data_SRV=self.getServiceByUUID(self._dataUUID)

		self.data = self.data_SRV.getCharacteristics()[0]
		
		#print("== CTRL ==")
		#print(self.ctrl_SRV.getCharacteristics())
		self.ctrl = self.ctrl_SRV.getCharacteristics()[0]

if __name__ == "__main__":
	import time

	cHM10 = HM10("7C:66:9D:9A:6F:90")
	cHM10.ctrl.write(struct.pack("B", 0xff))
	#cHM10.ctrl.write(struct.pack("B", 0))
	
	while True:
		print(cHM10.data.read())
		print(cHM10.data.write("%s\n\r"%str(time.time())))
		time.sleep(1.0)

</pre>

Thanks for any hints!

**Comment by IanHarvey** [comment]
I can't really go anywhere with this at the minute, so I'm closing the issue. Let me know if you have any more information.

Thanks
Ian

**Comment by Toklandarr** [comment]
Using the same Module as the OP, turned on debugging, this is what I get:

```
[<btle.Characteristic instance at 0x76a25be8>, <btle.Characteristic instance at 0x76a25cb0>, <btle.Characteristic instance at 0x76a25dc8>, <btle.Characteristic instance at 0x76a25e40>, <btle.Characteristic instance at 0x76a25eb8>]
None
None
None
Sent:  wrr 12 302c312c3230302c302c300a

Got: 'rsp=$ntfy hnd=h12 d=b72656365697665640D0A72656365697665643A30\n'
Notification: 18 sent data 72656365697665640d0a72656365697665643a30
Got: 'rsp=$ntfy hnd=h12 d=b2C302C32\n'
Notification: 18 sent data 2c302c32
Got: 'rsp=$ntfy hnd=h12 d=b30300D0A\n'
Notification: 18 sent data 30300d0a
Got: 'rsp=$wr\n'
None
Sent:  rd 12

Got: 'rsp=$ntfy hnd=h12 d=b72656365697665640D0A72656365697665643A32\n'
Notification: 18 sent data 72656365697665640d0a72656365697665643a32
Got: 'rsp=$ntfy hnd=h12 d=b30302C302C\n'
Notification: 18 sent data 30302c302c
Got: 'rsp=$ntfy hnd=h12 d=b300D0A\n'
Notification: 18 sent data 300d0a
Got: 'rsp=$rd d=b00\n'

Sent:  wrr 12 2d312c302c302c302c3230300a

Got: 'rsp=$wr\n'
None
Sent:  rd 12

Got: 'rsp=$ntfy hnd=h12 d=b72656365697665640D0A72656365697665643A30\n'
Notification: 18 sent data 72656365697665640d0a72656365697665643a30
Got: 'rsp=$ntfy hnd=h12 d=b2C302C3230\n'
Notification: 18 sent data 2c302c3230
Got: 'rsp=$ntfy hnd=h12 d=b300D0A\n'
Notification: 18 sent data 300d0a
Got: 'rsp=$rd d=b00\n'

1
Sent:  wrr 12 312c322c3230302c302c300a

Got: 'rsp=$wr\n'
None
Sent:  rd 12

Got: 'rsp=$ntfy hnd=h12 d=b72656365697665640D0A72656365697665643A32\n'
Notification: 18 sent data 72656365697665640d0a72656365697665643a32
Got: 'rsp=$ntfy hnd=h12 d=b30302C302C300D0A\n'
Notification: 18 sent data 30302c302c300d0a
Got: 'rsp=$rd d=b00\n'

Sent:  wrr 12 302c312c302c302c3230300a

Got: 'rsp=$wr\n'
None
Sent:  rd 12

Got: 'rsp=$ntfy hnd=h12 d=b72656365697665640D0A72656365697665643A30\n'
Notification: 18 sent data 72656365697665640d0a72656365697665643a30
Got: 'rsp=$ntfy hnd=h12 d=b2C302C3230300D0A\n'
Notification: 18 sent data 2c302c3230300d0a
Got: 'rsp=$rd d=b00\n'
```

**Comment by erazor83** [comment]
thanks for reporting this... I still have the hardware somewhere but am missing time for testing :-(
