### ISSUE TITLE
in raspberry pi + bluez 5.40 Traceback (most recent call last):   File "btle.py", line 675, in <module>     raise ImportError("Cannot find required executable '%s'" % helperExe) ImportError: Cannot find required executable '/home/pi/bt/bluepy/bluepy/bluepy-helper'

### ISSUE THREAD

**Issue by dammianhr** [IanHarvey/bluepy#139]
hi! i have this errror
Traceback (most recent call last):
  File "btle.py", line 675, in <module>
    raise ImportError("Cannot find required executable '%s'" % helperExe)
ImportError: Cannot find required executable '/home/pi/bt/bluepy/bluepy/bluepy-helper'

when try to connect to a iFever device with rpi2

**Comment by DavidLP** [comment]
This answer is late, but for reference. This might be related to #158. You could try to call `make` within  `/home/pi/bt/bluepy/bluepy/`

**Comment by IanHarvey** [comment]
There's lots of discussion about installation issues in #158, and #223 is closely related.

I believe these are both now fixed, but who can tell?
