### ISSUE TITLE
RaspberryPi: DefaultDelegate BTLEException 

### ISSUE THREAD

**Issue by alokranjan007** [IanHarvey/bluepy#142]
![error](https://cloud.githubusercontent.com/assets/19912807/17245175/eb56b410-55a2-11e6-98bd-95dfe4dc7a4a.PNG)

- [x] `from bluepy.bluepy.btle import peripheral, ADDR_TYPE_PUBLIC, AssignedNumbers
DefaultDelegate, BTLEException
ImportError: No module named `bluepy.bluepy.btle`` I have performed the scan operation and it is showing the available device mac address, but repeatedly I am getting the same error. Note: I have configured the bluepy by cloning it from GitHub

**Comment by hardwarewinjit** [comment]
hi, i am getting error "ImportError: No module named bluepy.bluepy.btle" while running code using bluepy lib on my rpi 3
 please help

Thank you
