### ISSUE TITLE
Bluepy's dependence on the current Bluez version?

### ISSUE THREAD

**Issue by dfclark** [IanHarvey/bluepy#144]
I've installed Bluez 5.41 on my Raspberry Pi - does the Bluez-5.29 folder in the Bluepy project have to be replaced before the package is built and installed?

**Comment by IanHarvey** [comment]
No, bluepy has its own independent copy of all the C source it needs (for building _bluepy-helper_). It doesn't depend on any other system executables, so will coexist with Blue 5.41 without needing alterations.

Thanks
Ian
