### ISSUE TITLE
Service.getDescriptors

### ISSUE THREAD

**Issue by helenst** [IanHarvey/bluepy#147]
The docs for `Peripheral.getDescriptors()` say:

> Again, it’s usually more convenient to use `Service.getDescriptors()` to get the descriptors associated with a particular service.

However, there is no such method on `Service`.

**Comment by IanHarvey** [comment]
`Service.getDescriptors()` and `Characteristic.getDescriptors()` should be working in commit 5c107d1 and later (see also pull request #89). 

Thanks for pointing this out,
Ian
