### ISSUE TITLE
Notifications?

### ISSUE THREAD

**Issue by jssvgs** [IanHarvey/bluepy#16]
Hi Ian,

I like a lot your code, because it is very elegant and nice. I have using it but I have some speed issues that I think that would be solved activating the notification mode of the sensors in a ST. Do you have any suggestion about it? Any plan to continue this project in this line?

Thanks for your work.

**Comment by IanHarvey** [comment]
So, notifications were implemented in version 0.9.0 of bluepy, which I've just made some documentation for - see http://ianharvey.github.io/bluepy-doc/notifications.html .

The SensorTag keypress service code uses it as an example.

**Comment by parkerlreed** [comment]
@IanHarvey Do you have a functioning example? (Not just overview) I've been trying to implement that script as is and python2 and 3 complain about tabs/spaces/etc for that p variable. I've tried fixing it to no avail.

**Comment by IanHarvey** [comment]
Ah - if you just cut-and-paste the code in the documentation there will be a problem with this bit:
```python
    def handleNotification(self, cHandle, data):
        # ... perhaps check cHandle
        # ... process 'data'
```
...because Python need some actual code after the `def`, not just comments. Try something like this:
```python
    def handleNotification(self, cHandle, data):
        print "Data is", repr(data)
```

**Comment by prasanthgiri2010** [comment]
hi 
My doubt is how to enable notifications- sensorTag for multible characteristics like temperature , humidity ???
Please provide some example
