### ISSUE TITLE
working versions

### ISSUE THREAD

**Issue by timcoote** [IanHarvey/bluepy#175]
I can confirm that the package seems to work on fedora 25 with both python 2.7 and 3.5. I've not pushed it very hard and cannot see any standard smoke tests that I could run (unsurprising as there's an external dependency on a bt device)

**Comment by IanHarvey** [comment]
Good to know, thanks.

The smoke tests I have are generally the `blescan` and `sensortag` scripts which get installed in `/usr/local/bin`. If they're working (the "keypress service" on a sensortag tests whether notifications are working) then most basic functionality is intact.

Thanks
Ian
