### ISSUE TITLE
no module named btle

### ISSUE THREAD

**Issue by sdy1130** [IanHarvey/bluepy#197]
<img width="276" alt="screen shot 2017-06-13 at 4 50 53 pm" src="https://user-images.githubusercontent.com/15865107/27085629-86742206-5058-11e7-8986-1a6df81090ad.png">

I installed this library as instructed and I get this error when I run the same code...

**Comment by BillyNate** [comment]
''

**Comment by PrzemoF** [comment]
pip or local build? Did you try import bluepy.btle ?
Also you can always try to use your distro reporitory to install bluepy.

**Comment by IanHarvey** [comment]
If you installed the library with pip, the recommended way is:
```python
from bluepy import btle
```

Does this work for you? Maybe the documentation needs updating to make this clear.

**Comment by g2kokaro** [comment]
I am having the same issue. I'm running Ubuntu 18.04 with Python 3.6.5. I've tried installing via pip3 both with and without sudo and installing from source.
![image](https://user-images.githubusercontent.com/5863654/41812363-8dc789a8-76ef-11e8-8bbe-d484307d3913.png)

**Comment by willm1001** [comment]
If you have the bluepy source directory in the same directory as the python file that is calling bluepy, delete, move, or rename it. I git cloned the bluepy source to my home directory and also had created my python test file in my home directory and it caused this problem. Once I removed the bluepy source directory, I was able to call bluepy without issue.

Further info:
You will need libglib2.0-dev for the glib.h requirement...
```
sudo apt-get install libglib2.0-dev
wget <path to bluepy source tarball, get from the download link above>
tar -xzvf bluepy-1.0.5.tar.gz
cd bluepy-1.0.5
sudo python3 setup.py build
sudo python3 setup.py install
```

**Comment by jml6969** [comment]
from bluepy import btle
from bluepy import sensortag (*from bluepy.bluepy import sensortag won't work!*)

if you have been doing the example from Orestis from github (before coming to this example) make sure to change the name of file (sensortag.py) of this example to something else. This can create issue.
