### ISSUE TITLE
Failed to install bluepy with all means

### ISSUE THREAD

**Issue by fonics** [IanHarvey/bluepy#199]
I have python 3.4 installed (64) .

I have tried " pip install bluepy" with no success.
![error](https://user-images.githubusercontent.com/7887105/27657790-1351e5ae-5c4e-11e7-8a98-c54789a4c0d2.PNG)

**Comment by jan-xyz** [comment]
It looks like you are trying to use the library on Windows.
The first sentence in the [README](https://github.com/IanHarvey/bluepy/blob/master/README.md) says:
```
Python interface to Bluetooth LE on Linux.
```

**Comment by fonics** [comment]
thanks @jan-xyz  sorry for the inconvenience

**Comment by abdulwajid016** [comment]
I got this error in installing bluepy
I want to get the raw data from BLE Beacon 
If you guys solve my problem then i will be really greatful to you
![error](https://user-images.githubusercontent.com/42087793/50433318-65ed3980-088c-11e9-9b6e-d9ce1e52af63.PNG)
