### ISSUE TITLE
How to write to a Characteristic

### ISSUE THREAD

**Issue by mcsarge** [IanHarvey/bluepy#20]
Not really an Issue, but I have a question: 
The device I am trying to communicate with requires that I set the value of a characteristic and then write to the characteristic. The response from this write contains the result of the command. For instance if I write "read temp\r" I get back "66.0". I have looked through your code, but not being an expert in Python, I am having a bit of a time figuring out how I write a string (like "status") to the characteristic and then get back the response. I am pretty sure this is something simple, but I am stuck.

**Comment by IanHarvey** [comment]
I have now (version 0.9.0, just pushed) made some proper arrangements for handling notifications from peripherals. It lets you register an object to be called whenever a notification is sent, and has a method which waits for notifications with a selectable timeout.

The main documentation page describing this is at http://ianharvey.github.io/bluepy-doc/notifications.html
If you're still developing this, I'd be happy to hear whether this is useful.

Thanks
Ian
