### ISSUE TITLE
Testing bluepy

### ISSUE THREAD

**Issue by PrzemoF** [IanHarvey/bluepy#22]
I'm quite sure it's not an issue with bluepy, but I need confirmation. That's a discovery session with a heart rate sensor:
pi@occberry ~/bluepy/bluepy $ sudo hciconfig hci0 up
pi@occberry ~/bluez/bluez-5.26 $ sudo hcitool lescan
LE Scan ...
90:59:AF:16:93:12 (unknown)
90:59:AF:16:93:12 JipulseHrRateBT4.0
[..]
pi@occberry ~/bluepy/bluepy $ sudo python btle.py 90:59:AF:16:93:12
Connecting to: 90:59:AF:16:93:12
Service <uuid=Generic Attribute handleStart=12 handleEnd=15> :
    Characteristic <2a05>
    -> Error from Bluetooth stack (comerr)
Service <uuid=Generic Access handleStart=1 handleEnd=11> :
    Characteristic <Device Name>
    -> ''
    Characteristic <2a01>
    -> '\x00\x00'
    Characteristic <2a02>
    -> '\x00'
    Characteristic <2a03>
    -> '\x00\x00\x00\x00\x00\x00'
    Characteristic <2a04>
    -> 'P\x00\xa0\x00\x00\x00\xe8\x03'
Service <uuid=ffe0 handleStart=52 handleEnd=65535> :
    Characteristic <ffe1>
    -> Error from Bluetooth stack (comerr)
Service <uuid=fff0 handleStart=35 handleEnd=51> :
    Characteristic <fff1>
    -> '\x01'
    Characteristic <fff2>
    -> '\x02'
    Characteristic <fff3>
    -> Error from Bluetooth stack (comerr)
    Characteristic <fff4>
    -> Error from Bluetooth stack (comerr)
    Characteristic <fff5>
    -> Error from Bluetooth stack (comerr)
Service <uuid=Device Information handleStart=16 handleEnd=34> :
    Characteristic <2a23>
    -> '\x12\x93\x16\x00\x00\xafY\x90'
    Characteristic <Model Number String>
    -> 'Model Number\x00'
    Characteristic <Serial Number String>
    -> 'Serial Number\x00'
    Characteristic <Firmware Revision String>
    -> 'Firmware Revision\x00'
    Characteristic <Hardware Revision String>
    -> 'Hardware Revision\x00'
    Characteristic <Software Revision String>
    -> 'Software Revision\x00'
    Characteristic <Manufacturer Name String>
    -> 'Manufacturer Name\x00'
    Characteristic <2a2a>
    -> '\xfe\x00experimental'
    Characteristic <2a50>
    -> '\x01\r\x00\x00\x00\x10\x01'

Does it look OK conparing to other BLE devices?
That sensor doesn't work properly with android, so I guess that the vendor at least partially ignored BLE specification. P.S. Running the bluepy-helper doesn't make any difference.

**Comment by IanHarvey** [comment]
Hi Przemo,

The 'comerr' errors are what I'd expect if you're calling read() on characteristics which don't allow reading. It looks like this got fixed in pull request #32 (specifically, commit 721dc48), so I'll close this issue.

Cheers
Ian
