### ISSUE TITLE
Raspberry in BLE slave mode 

### ISSUE THREAD

**Issue by roudot** [IanHarvey/bluepy#232]
Hello,

I would like to configure a raspberry pi 3 in slave mode BLE to simulate a sensor,  but it seems not possible do to it with bluepy. Do you know how to do it ?

Thank you in advance.
Michel

**Comment by IanHarvey** [comment]
Hi, this isn't possible with `bluepy`.

You can look at some experimental code I made to do this at https://github.com/IanHarvey/bluepy.device, although this isn't going to receive any more development from me.

I'm currently working with the `bleson` project (https://github.com/TheCellule/python-bleson) to help develop a pure-Python Bluetooth LE stack which will operate as a BLE peripheral.

Thanks
Ian
