### ISSUE TITLE
Failed building wheel for bluepy

### ISSUE THREAD

**Issue by Roflhaus** [IanHarvey/bluepy#238]
I wouldn't ask here if I didn't feel that I've done everything that I could, so keep that in mind before flaming me.

- I'm installing this on CentOS 7 running on a raspberry pi 3.
- I've installed Development Tools.
- I have Python 2.7.5
- I have gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
- #pip list
    decorator (3.4.0)
    iniparse (0.4)
    pip (9.0.1)
    pycurl (7.19.0)
    pygobject (3.22.0)
    pygpgme (0.3)
    pyliblzma (0.5.3)
    pyxattr (0.5.1)
    setuptools (36.7.2)
    slip (0.4.0)
    slip.dbus (0.4.0) 
    urlgrabber (3.10)
    wheel (0.30.0)
    yum-metadata-parser (1.1.4)

The error that I see is " error: No such file or directory".  Doesn't seem related to a missing dependency, but it wouldn't be the first time I was wrong.

Any help is appreciated.  Thanks.

=========================================
Building wheels for collected packages: bluepy
  Destination directory: /tmp/tmpnkroGIpip-wheel-
  Running command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-o7dU2I/bluepy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpnkroGIpip-wheel- --python-tag cp27
  running bdist_wheel
  running build
  running build_py
  Working dir is /tmp/pip-build-o7dU2I/bluepy
  execute make -C ./bluepy clean
  error: No such file or directory
  Failed building wheel for bluepy

**Comment by avandermeer** [comment]
what was your solution?
