### ISSUE TITLE
Error when entering make

### ISSUE THREAD

**Issue by 3man1992** [IanHarvey/bluepy#266]
OpenBCI use this library. And when I follow their instructions to enter make within bluepy I get the following: 

`lfreemans-MacBook-Pro:bluepy lfreeman$ make
gcc -L. -Os -g -Wall -Werror -DHAVE_CONFIG_H -I./bluez-5.29/attrib -I./bluez-5.29 -I./bluez-5.29/lib -I./bluez-5.29/src -I./bluez-5.29/gdbus -I./bluez-5.29/btio -I/usr/local/Cellar/glib/2.56.1/include/glib-2.0 -I/usr/local/Cellar/glib/2.56.1/lib/glib-2.0/include -I/usr/local/opt/gettext/include -I/usr/local/Cellar/pcre/8.42/include -o bluepy-helper bluepy-helper.c ./bluez-5.29/lib/bluetooth.c ./bluez-5.29/lib/hci.c ./bluez-5.29/lib/sdp.c ./bluez-5.29/lib/uuid.c ./bluez-5.29/attrib/att.c ./bluez-5.29/attrib/gatt.c ./bluez-5.29/attrib/gattrib.c ./bluez-5.29/attrib/utils.c ./bluez-5.29/btio/btio.c ./bluez-5.29/src/log.c ./bluez-5.29/src/shared/mgmt.c ./bluez-5.29/src/shared/crypto.c ./bluez-5.29/src/shared/att.c ./bluez-5.29/src/shared/queue.c ./bluez-5.29/src/shared/util.c ./bluez-5.29/src/shared/io-glib.c ./bluez-5.29/src/shared/timeout-glib.c -L/usr/local/Cellar/glib/2.56.1/lib -L/usr/local/opt/gettext/lib -lglib-2.0 -lintl -Wl,-framework -Wl,CoreFoundation
In file included from bluepy-helper.c:36:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/lib/bluetooth.c:38:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/lib/hci.c:44:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/lib/sdp.c:45:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/lib/uuid.c:33:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/attrib/att.c:35:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/attrib/gatt.c:34:
In file included from ./bluez-5.29/lib/sdp.h:35:
./bluez-5.29/lib/bluetooth/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/attrib/gattrib.c:36:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/attrib/utils.c:32:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/btio/btio.c:39:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/src/shared/mgmt.c:33:
./bluez-5.29/lib/bluetooth.h:36:10: fatal error: 'endian.h' file not found
#include <endian.h>
         ^~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/src/shared/crypto.c:33:
./bluez-5.29/src/shared/util.h:27:10: fatal error: 'byteswap.h' file not found
#include <byteswap.h>
         ^~~~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/src/shared/att.c:34:
./bluez-5.29/src/shared/util.h:27:10: fatal error: 'byteswap.h' file not found
#include <byteswap.h>
         ^~~~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/src/shared/queue.c:28:
./bluez-5.29/src/shared/util.h:27:10: fatal error: 'byteswap.h' file not found
#include <byteswap.h>
         ^~~~~~~~~~~~
1 error generated.
In file included from ./bluez-5.29/src/shared/util.c:38:
./bluez-5.29/src/shared/util.h:27:10: fatal error: 'byteswap.h' file not found
#include <byteswap.h>
         ^~~~~~~~~~~~
1 error generated.
make: *** [bluepy-helper] Error 1
lfreemans-MacBook-Pro:bluepy lfreeman$ `

Even though I installed glib. Any help? I've been stuck on this for hours.

Thank you in advance,

L

Edit: "Failed on MacOS High Sierra. Tried on Ubuntu 16 & 18. Worked fine there."

**Comment by IanHarvey** [comment]
Bluepy isn't supported on Mac OS, sorry. Some discussion of possible alternatives is at issue #44 .
