### ISSUE TITLE
Accelerometer equation

### ISSUE THREAD

**Issue by Grantx** [IanHarvey/bluepy#28]
Hi the accelerometer equation devides by 64.

I found this to be inacurate as it did not give a resultant acceleration of 1 g when the sensortag was still on a table. I changed the code to devide by 16 instead and got better output.

Please someone do a simple test to verify this.

**Comment by IanHarvey** [comment]
It looks like the value reported changed between v1.4 and v1.5 of the firmware. v1.5 seems to report values 1/4 as big as previously.

If I can come up with a reliable way of distinguishing between versions I'll check in a fix.

Thanks
Ian
