### ISSUE TITLE
ImportError: No module named btle

### ISSUE THREAD

**Issue by mazhenlong** [IanHarvey/bluepy#294]
Hi, when I input 
`from bluepy.btle import Characteristic` , 
it returns
 `ImportError: No module named btle`.
I tried python 2.7 and 3.5, the same problem.
And I have tried the solution of #112 , it doesn't work.

**Comment by PrzemoF** [comment]
Can you post the result of:
``import pip ; sorted(["%s==%s" % (i.key, i.version) for i in pip.get_installed_distributions()])

**Comment by PrzemoF** [comment]
Do you have pip installed? What system do you use? How did you install bluepy?

**Comment by PrzemoF** [comment]
From source files, so you did something like:
'sudo python setup.py install' 
?
Please post:
'find /usr -name "bluepy"'

**Comment by tom-hooper** [comment]
I had the same issue. something wrong with the installer in pip 
I ended up running `sudo python3 setup.py install` to get it to put the files in the right path.

output for  `find /usr -name "bluepy"`
`/usr/local/lib/python3.6/dist-packages/bluepy-1.3.0-py3.6.egg/bluepy`

this was a real pain in the ass to find. pip stuffed up the installs.

**Comment by McMacaron** [comment]
> sudo python setup.py install

Absolutely do not understand what you are talking about. But I have the  same issue.
