### ISSUE TITLE
Read RSSI from bluepy

### ISSUE THREAD

**Issue by vielmetti** [IanHarvey/bluepy#43]
As mentioned in the readme, an open issue to support RSSI in bluepy.

**Comment by IanHarvey** [comment]
There is now partial support for getting the RSSI - if the device is broadcasting advertising data you can now use a 'Scanner' class to receive these. The RSSI can be retrieved from the ScanEntry object - see http://ianharvey.github.io/bluepy-doc/scanentry.html#properties.
