### ISSUE TITLE
Support for Mac OS X (10.9, 10.10)

### ISSUE THREAD

**Issue by vielmetti** [IanHarvey/bluepy#44]
bluepy and bluepy-helper depend on Linux's bluez. 

It would be a useful thing to have an abstraction layer that let you write the same python code for both Mac OS X and Linux, along the lines of what noble does for node.js.

Tracking any specific issues here.

**Comment by wind-rider** [comment]
https://bitbucket.org/OscarAcena/pygattlib does this, you can have a look at how they integrated the OSX part and the abstraction layer there. I would also say that bluepy could improve upon this point - being cross platform would be a major advantage.

**Comment by mritchie712** [comment]
@wind-rider are you syaing pygattlib supports OSX? When I try to install it on OSX I get:

    OSError: Not supported OS

**Comment by wind-rider** [comment]
@mritchie712 I'm sorry, I must have confused it.

However here https://github.com/matthewelse/bleep/ says to have experimental OSX support besides Linux support, with two backends as shown in https://github.com/matthewelse/bleep/blob/master/bleep/backend.py.

This could be an example for bluepy?

**Comment by mritchie712** [comment]
@wind-rider that looks promising, thanks!

**Comment by bretcj7** [comment]
@mritchie712  did you get past the issue?  I'm battling the same right now.

**Comment by mritchie712** [comment]
No, I ended up using ionic (JavaScript framework) instead

**Comment by IanHarvey** [comment]
Realistically, Mac OS support isn't going to be added to Bluepy any time soon. 

Interested parties might want to look at https://github.com/TheCellule/python-bleson, which supports Mac OS but is still somewhat under development.
