### ISSUE TITLE
line_reader is not working

### ISSUE THREAD

**Issue by ShawnHymel** [IanHarvey/bluepy#50]
The newest merge seems to have broken the _getResp() method. With the following test code:

>from bluepy.btle import Peripheral
>p = Peripheral("xx:xx:xx:xx:xx:xx")

I get the following error:

>  File "/home/edison/bluepy/bluepy/btle.py", line 188, in __init__
>   self.connect(deviceAddr, addrType)
>connect: Device or resource busy (16)
> File "/home/edison/bluepy/bluepy/btle.py", line 298, in connect
>  rsp = self._getResp('stat')
>  File "/home/edison/bluepy/bluepy/btle.py", line 250, in _getResp
 >   rv = ''.join(map(chr, rv))
>TypeError: an integer is required
>Exception TypeError: 'an integer is required' in <bound method Peripheral.__del__ of <bluepy.btle.Peripheral instance at 0xb72b98ec>> ignored

**Comment by IanHarvey** [comment]
I've now removed the line_reader stuff from the mainline code, as I don't think it's actually necessary.

Thanks
Ian
