### ISSUE TITLE
Response time

### ISSUE THREAD

**Issue by brokenZorg** [IanHarvey/bluepy#51]
Hi,

Have you got any idea about the response time of the method write from the characteristic class ?
By response time, I mean time from the call of this method until the reception from the Peripheral.

I wrote a simple program on a raspberry which receive data by udp and send it to a bluetooth peripheral using bluepy.
I measure 40ms in average between the udp sending and the bluetooth reception. I would like it to be a bit faster, so I try to improve my program on the raspberry.
I don't know if this response time is due to a bad implementation of the udp reception, I made a non blocking reception in a thread which fill a queue. In another thread this queue is read and send by bluetooth. But it seems that threads can be tricky and maybe I did something bad.
Or maybe this response time is normal and is due to the time taking by the write method to execute, I don't know. Have you ever measured it ?

Anyway, thanks for this API, your work really helped me a lot !

**Comment by IanHarvey** [comment]
The response time will depend on the 'connection interval' parameter which is determined when the connection is set up. The peripheral won't keep its radio on all the time (to save battery), but instead it agrees with the 'central' a time interval between sending packets.

I'm afraid bluepy doesn't provide any way to vary the connection interval at the minute.
