### ISSUE TITLE
Humidity Sensor

### ISSUE THREAD

**Issue by JTrantow** [IanHarvey/bluepy#52]
Uses the humidity sensor scaling for the older sensorTag instead of scaling for HTC1000 used in newer CC2650 sensorTag. Could keep track of which sensorTag is in use and use the appropriate scaling.

SHT21 (old sensorTag)
humidity =-6+125*raw/65536
temperature =-4686 + 175.72*raw/65536

HDC1000 (CC2650 sensorTag)
humidity = (raw/65536)*100
temperature = (raw/65536)*165 - 40

Note: at least one of these values should also have some status bits masked off and attention should be paid to data types and rounding.

**Comment by IanHarvey** [comment]
I've just added support for the CC2650 sensortag (in sensortag.py - there is not a separate Sensortag2650.py any more), which now has the HDC1000 sensor calculation in.

Thanks
Ian
