### ISSUE TITLE
Works great until I try to use the write() method

### ISSUE THREAD

**Issue by idealmundo** [IanHarvey/bluepy#66]
I've had success using bluepy to connect to and read characteristics from the raspberry pi, but when I try to use the write() method, it isn't working:

```
baddr = 'xx:xx:xx:xx:xx:xx'
device = btle.Peripheral(baddr,'random')
chars = device.getCharacteristics()

chars[9].read()
```

returns '\x00'

but
    chars[9].write('02')

and
    chars[9].write('\x02')

accomplish nothing, because if I issue again

```
chars[9].read()
```

again I get '\x00'

with gatttool in bash the following works:

```
gatttool -b xx:xx:xx:xx:xx:xx  -t random --char-write 0x001b -n 02
```

How can I pass data to a characteristic using the write() method?

Thanks!

**Comment by IanHarvey** [comment]
Firstly, is the characteristic at chars[9] actually writable? If you run 'python btle.py xx:xx:xx:xx:xx:xx' it should give a list of all characteristics and their properties. It would be helpful to have the output from this command here.
