### ISSUE TITLE
Anything blocking pypi?

### ISSUE THREAD

**Issue by erikcw** [IanHarvey/bluepy#68]
Now that we have a `setup.py` -- is there anything blocking a release to pypi?

**Comment by IanHarvey** [comment]
As it happens, there were a quite a few little problems to be sorted out, but there is now a bluepy package up on PyPi - see https://pypi.python.org/pypi/bluepy/1.0.2

If you want to give **sudo pip install bluepy** a go, please let me know whether it works.

Cheers
Ian

**Comment by IanHarvey** [comment]
v1.0.3 is now available (with some minor fixes to documentation), at https://pypi.python.org/pypi?:action=display&name=bluepy&version=1.0.3 

I guess this is working for other people as well as me, so I'll close this.
