### ISSUE TITLE
raw BLE advertisement scanning

### ISSUE THREAD

**Issue by msnyder415** [IanHarvey/bluepy#70]
Hi Ian 

I noticed the comment below on your readme for the project:
```
- Implement 'hcitool lescan' functionality
```

Are you aware of any python libs that will expose the raw advertisement payloads? 
Any idea if / when yours may? 

Thanks!

**Comment by ShuffleBox** [comment]
I've used PyGattlib for BLE device discovery. https://bitbucket.org/OscarAcena/pygattlib
Perhaps worth a look.

**Comment by IanHarvey** [comment]
Scanning is now available (albeit there are no docs yet) in v/0.9.10, just out.

The raw advertisement payloads come over as the _rawData_ attribute of a _ScanEntry_ object, which is passed to the delegate registered with a _Scanner_ object. There's now a program **test/scan.py** which should give you the basic idea.

Thanks
Ian

**Comment by NateEaton** [comment]
I know this is a stale topic but I need the same thing, access to the raw advertisement data. I don't see any ref to rawData in the 0.9.11 docs... was it dropped? Or just still not documented?

**Comment by B03901108** [comment]
I share similar feedback with @NateEaton that some class members like rawData and scanData are not available in official documents. I had to find them by diving into the source code (btle.py). Just for the convenience of others working on low-level BLE stuff, rawData provides the raw payload of the latest observed advertisement, while scanData provides the accumulated AD Data keyed by AD Type. (Both show payload/advertising data in bytes.)

Suppose the current scan request invites no scan responses, but an earlier scan request invited a scan response. rawBinary would imply the lack of scan response, while scanData would keep some information from the earlier scan response.
