### ISSUE TITLE
Upgrade to BlueZ-5.35

### ISSUE THREAD

**Issue by rmoshiri** [IanHarvey/bluepy#78]
I tried to replace the bluez-5.29 in this package, with the latest bluez-5.35 release.
Got compile error in "bluepy-helper.c", line 462. Made minor change there, and it 
seems to work. I just set the new flag passed to the subroutine as "false". That
should be OK as it is for an external encryption option.

Just in case you want to upgrade and test it, below were the chaanges:

sudo leafpad Makefile         (Change Bluez version's Directory)
                                BLUEZ_PATH=../bluez-5.35
 sudo leafpad bluepy-helper.c  (Add "false" for a 3rd/new parameter RE external encryption)
                                Line 462: attrib = g_attrib_new(iochannel, mtu, false);

**Comment by raplin** [comment]
FYI This fix is required & works when building against bluez 5.37 (latest at time of writing) also. Thanks!

**Comment by IanHarvey** [comment]
bluepy 1.2.0 now uses code from bluez 5.47, so I'll close this issue now.
