### ISSUE TITLE
Needs a way to pick which adapter to use.

### ISSUE THREAD

**Issue by ali1234** [IanHarvey/bluepy#79]
If the system has a bluetooth adapter which doesn't support LE there is no way to tell bluepy to not use it. It always tries to use the one most recently connected to the system.

**Comment by IanHarvey** [comment]
Hi,

I've just pushed a big bunch of contributions & fixes to master. The Peripheral constructor now takes an optional 'iface' parameter, which is an index (0, 1, ...) for the interface to use. Hopefully this will be just what you need.

Thanks
Ian
