### ISSUE TITLE
Unable to access Accelerometer data from CC2650_SensorTag

### ISSUE THREAD

**Issue by Vijayenthiran** [IanHarvey/bluepy#80]
I tried to read the Temperature data from the Sensor tag and I was able to do it. But reading accelerometer data throws error. This is the command I executed:
```shell
pi@raspberrypi ~/bluepy/bluepy $ sudo python sensortag.py 68:C9:0B:06:64:84 -n 5 -A
```

Which returned the following:

```shell
Connecting to 68:C9:0B:06:64:84
Traceback (most recent call last):
  File "sensortag.py", line 293, in <module>
    main()
  File "sensortag.py", line 257, in main
    tag.accelerometer.enable()
  File "sensortag.py", line 21, in enable
    self.service = self.periph.getServiceByUUID(self.svcUUID)
  File "/home/pi/bluepy/bluepy/btle.py", line 365, in getServiceByUUID
    svc = Service(self, uuid, rsp['hstart'][0], rsp['hend'][0])
KeyError: 'hstart'
```

**Comment by IanHarvey** [comment]
So I've just (tag v/0.9.12) added some support for the CC2650 sensortag. This is in the main sensortag.py file, which now detects which version of sensotag it is and selects the right peripherals. There isn't a need for a separate Sensortag2650.py file any more.
