### ISSUE TITLE
Scan related responses leak across running bluepy-helpers

### ISSUE THREAD

**Issue by jspaletavert** [IanHarvey/bluepy#85]
I was testing out the Scan features in the contrib branch  while trying to run multiple devices. 

Any data sent to stdout from the registered mgmt\* functions leak across all running bluepy-helper processes and screw up the communication for the Peripherals.

I've got a local fix by introducing a cmdline argument to bluepy-helper that will enable the scan specific mgmt functions  Then I make sure the Scan object adds the argument to the helper popen call.  

I'll do up a pull request for you right now.

**Comment by IanHarvey** [comment]
There have been a lot of fixes between the contrib branch and current trunk code.

If this is still a problem in the latest code (b3f3e4c), could you let me know how to reproduce the issue? I've checked that, e.g. running `blescan` in one window while `sensortag` is connected to a device in another works OK.
