### ISSUE TITLE
Unexpected "Service [..] not found" error when UUID already indicates service

### ISSUE THREAD

**Issue by hoonkai** [IanHarvey/bluepy#92]
Hi

I'm using TI BLE's SimpleBLEPeripheral code on the GATT server which gives a UUID

`0000fff0-0000-1000-8000-00805f9b34fb`

When sensortag.py is modified with the following

``````
def _TI_UUID(val):
    return UUID("%08X-0000-1000-0000-000000000000" % (0x00000000+val))

...

class SimpleGatt(SensorBase):
    svcUUID  = _TI_UUID(0xFFF0) # Simple Profile Servce UUID
    dataUUID = _TI_UUID(0xFFF1) # SIMPLEPROFILE_CHAR1_UUID
    ctrlUUID = _TI_UUID(0xFFF2) # SIMPLEPROFILE_CHAR2_UUID

    def __init__(self, periph):
        SensorBase.__init__(self, perish)```
``````

and enabling it properly in `main()`, it fails to identify the FFF0 service and gives this error:

```
bluepy/bluepy/btle.py", line 408, in getServiceByUUID
raise BTLEException(BTLEException.GATT_ERROR, "Service %s not found" % (uuid.getCommonName()))
btle.BTLEException: Service f000fff0-0451-4000-b000-000000000000 not found
```

The UUID already indicates the FFF0 service and `SimpleGatt` already has `FFF0` as its `svcUUID`. What could be causing the failure?

Any help will be appreciated.

**Comment by IanHarvey** [comment]
My guess is that you're somehow not running the code you've just edited, as the service which isn't being found is `f000fff0-0451-4000-b000-000000000000`, and not `0000fff0-0000-1000-8000-00805f9b34fb` (as you say in the comment) or `0000FFF0-0000-1000-0000-000000000000` (as the code you posted will generate).

I would start with:

    class SimpleGatt(SensorBase):
        svcUUID  = UUID("0000fff0-0000-1000-8000-00805f9b34fb")
        print( "Looking for service: " + str(svcUUID))
    ....

Then the code will print exactly what it's looking for, or (if it doesn't print anything at all) you're running the wrong `sensortag.py` somehow.

**Comment by quique123** [comment]
Hoonkai, did you ever resolve this issue?
